In [1]:
# import relevant packages
from keras.datasets import mnist
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.utils import np_utils
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.utils import np_utils
from keras import backend as K
from keras import regularizers

Using TensorFlow backend.


In [46]:
# Create a simple dataset
X_train=np.array([[[1,2,3,4],[2,3,4,5],[5,6,7,8],[1,3,4,5]],[[-1,2,3,-4],[2,-3,4,5],[-5,6,-7,8],[-1,-3,-4,-5]]])
y_train=np.array([0,1])

In [47]:
# Normalize the inputs by dividing each value with the maximum value in dataset
X_train = X_train / 8

In [48]:
X_train[0]

array([[0.125, 0.25 , 0.375, 0.5  ],
       [0.25 , 0.375, 0.5  , 0.625],
       [0.625, 0.75 , 0.875, 1.   ],
       [0.125, 0.375, 0.5  , 0.625]])

In [50]:
# One hot encode the outputs
y_train = np_utils.to_categorical(y_train)

In [51]:
y_train[0]

array([1., 0.])

In [8]:
X_train = X_train.reshape(X_train.shape[0],X_train.shape[1],X_train.shape[1],1 ).astype('float32')

In [9]:
X_train.shape

(2, 4, 4, 1)

In [31]:
model = Sequential()
model.add(Conv2D(1, (3,3), input_shape=(4,4,1), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(10, activation='relu'))
model.add(Dense(2, activation='softmax'))
# Compile model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_6 (Conv2D)            (None, 2, 2, 1)           10        
_________________________________________________________________
max_pooling2d_6 (MaxPooling2 (None, 1, 1, 1)           0         
_________________________________________________________________
flatten_6 (Flatten)          (None, 1)                 0         
_________________________________________________________________
dense_11 (Dense)             (None, 10)                20        
_________________________________________________________________
dense_12 (Dense)             (None, 2)                 22        
Total params: 52
Trainable params: 52
Non-trainable params: 0
_________________________________________________________________


In [34]:
model.fit(X_train, y_train, epochs=100, batch_size=2, verbose=1)

Epoch 1/100
2/2 [==============================] - 0s 3ms/step - loss: 0.4062 - acc: 1.0000
Epoch 2/100
2/2 [==============================] - 0s 3ms/step - loss: 0.4037 - acc: 1.0000
Epoch 3/100
2/2 [==============================] - 0s 2ms/step - loss: 0.4012 - acc: 1.0000
Epoch 4/100
2/2 [==============================] - 0s 2ms/step - loss: 0.3986 - acc: 1.0000
Epoch 5/100
2/2 [==============================] - 0s 2ms/step - loss: 0.3961 - acc: 1.0000
Epoch 6/100
2/2 [==============================] - 0s 2ms/step - loss: 0.3935 - acc: 1.0000
Epoch 7/100
2/2 [==============================] - 0s 2ms/step - loss: 0.3911 - acc: 1.0000
Epoch 8/100
2/2 [==============================] - 0s 2ms/step - loss: 0.3886 - acc: 1.0000
Epoch 9/100
2/2 [==============================] - 0s 2ms/step - loss: 0.3861 - acc: 1.0000
Epoch 10/100
2/2 [==============================] - 0s 2ms/step - loss: 0.3835 - acc: 1.0000
Epoch 11/100
2/2 [==============================] - 0s 2ms/step - loss: 0.3811 

In [35]:
model.layers

In [52]:
model.layers[0].get_weights()

[array([[[[ 0.6502779 ]],
 
         [[ 0.3674555 ]],
 
         [[-0.04364061]]],
 
 
        [[[ 0.8205539 ]],
 
         [[ 0.5735873 ]],
 
         [[ 0.13939373]]],
 
 
        [[[-0.1292512 ]],
 
         [[ 0.05793982]],
 
         [[-0.03353929]]]], dtype=float32),
 array([-0.11086546], dtype=float32)]

In [37]:
names = [weight.name for layer in model.layers for weight in layer.weights]
weights = model.get_weights()

for name, weight in zip(names, weights):
    print(name, weight.shape)

conv2d_6/kernel:0 (3, 3, 1, 1)
conv2d_6/bias:0 (1,)
dense_11/kernel:0 (1, 10)
dense_11/bias:0 (10,)
dense_12/kernel:0 (10, 2)
dense_12/bias:0 (2,)


In [53]:
model.predict(X_train[0].reshape(1,4,4,1))

array([[0.8906642 , 0.10933578]], dtype=float32)